// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGlx5dQOOElg9Pjt54s1CGT-NNfkEywII',
    appId: '1:522351572968:web:06e8a4003a6f4bb464565d',
    messagingSenderId: '522351572968',
    projectId: 'chef-zaki',
    authDomain: 'chef-zaki.firebaseapp.com',
    storageBucket: 'chef-zaki.firebasestorage.app',
    measurementId: 'G-PJ5FKXSSZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOOjfhawQTqaRVu19k0T-oSLau8clQDZQ',
    appId: '1:522351572968:android:14ba7436e44d4cf264565d',
    messagingSenderId: '522351572968',
    projectId: 'chef-zaki',
    storageBucket: 'chef-zaki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyas2qCGLWJJT-K12CrY9sOFm33Dyjw0M',
    appId: '1:522351572968:ios:6f0438e60ba994fc64565d',
    messagingSenderId: '522351572968',
    projectId: 'chef-zaki',
    storageBucket: 'chef-zaki.firebasestorage.app',
    iosBundleId: 'com.example.chefZaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyas2qCGLWJJT-K12CrY9sOFm33Dyjw0M',
    appId: '1:522351572968:ios:6f0438e60ba994fc64565d',
    messagingSenderId: '522351572968',
    projectId: 'chef-zaki',
    storageBucket: 'chef-zaki.firebasestorage.app',
    iosBundleId: 'com.example.chefZaki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGlx5dQOOElg9Pjt54s1CGT-NNfkEywII',
    appId: '1:522351572968:web:7abdc5be6d3c28ab64565d',
    messagingSenderId: '522351572968',
    projectId: 'chef-zaki',
    authDomain: 'chef-zaki.firebaseapp.com',
    storageBucket: 'chef-zaki.firebasestorage.app',
    measurementId: 'G-FDBKZQJMEC',
  );

}